// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type LoginRequest struct {
	UserEmail    string `json:"userEmail" validate:"required"`
	UserPassword string `json:"userPassword" validate:"required"`
}

type LoginResponse struct {
	Token       string `json:"token"`
	Id          int64  `json:"id"`
	UserAccount string `json:"userAccount"`
	UserName    string `json:"userName"`
	UserAvatar  string `json:"userAvatar"`
	UserProfile string `json:"userProfile"`
	UserRole    string `json:"userRole"`
	CreateTime  string `json:"createTime"` // 修复：在接口层使用 string 或 int64
	UpdateTime  string `json:"updateTime"` // 修复：在接口层使用 string 或 int64
}

type RegisterRequest struct {
	UserEmail         string `json:"userEmail" validate:"required"`
	UserPassword      string `json:"userPassword" validate:"required"`
	UserCheckPassword string `json:"userCheckPassword" validate:"required"`
}

type RegisterResponse struct {
	Id int64 `json:"id"`
}
