// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type UserIDQueryRequest struct {
	Id SnowflakeID `form:"id"`
}

type LoginRequest struct {
	UserEmail    string `json:"userEmail" validate:"required"`
	UserPassword string `json:"userPassword" validate:"required"`
}

type LoginResponse struct {
	Token       string      `json:"token"`
	Id          SnowflakeID `json:"id"`
	UserAccount string      `json:"userAccount"`
	UserName    string      `json:"userName"`
	UserAvatar  string      `json:"userAvatar"`
	UserProfile string      `json:"userProfile"`
	UserRole    string      `json:"userRole"`
	CreateTime  string      `json:"createTime"` // 修复：在接口层使用 string 或 int64
	UpdateTime  string      `json:"updateTime"` // 修复：在接口层使用 string 或 int64
}

type RegisterRequest struct {
	UserEmail         string `json:"userEmail" validate:"required"`
	UserPassword      string `json:"userPassword" validate:"required"`
	UserCheckPassword string `json:"userCheckPassword" validate:"required"`
}

type RegisterResponse struct {
	Id SnowflakeID `json:"id"`
}

type UpdateMyUserRequest struct {
	UserName    *string `json:"userName,omitempty"`
	UserAvatar  *string `json:"userAvatar,omitempty"`
	UserProfile *string `json:"userProfile,omitempty"`
}

type UserProfileResponse struct {
	Id                   SnowflakeID `json:"id"`
	UserName             string      `json:"userName"`
	UserAvatar           string      `json:"userAvatar"`
	UserProfile          string      `json:"userProfile"`
	UserRole             string      `json:"userRole"`
	CreateTime           string      `json:"createTime"`
	UpdateTime           string      `json:"updateTime"`
	PictureCount         int64       `json:"pictureCount"`
	ApprovedPictureCount int64       `json:"approvedPictureCount"`
	PendingPictureCount  int64       `json:"pendingPictureCount"`
	RejectedPictureCount int64       `json:"rejectedPictureCount"`
}
