// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	picturesFieldNames          = builder.RawFieldNames(&Pictures{})
	picturesRows                = strings.Join(picturesFieldNames, ",")
	picturesRowsExpectAutoSet   = strings.Join(stringx.Remove(picturesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	picturesRowsWithPlaceHolder = strings.Join(stringx.Remove(picturesFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cachePicturesIdPrefix = "cache:pictures:id:"
)

type (
	picturesModel interface {
		Insert(ctx context.Context, data *Pictures) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*Pictures, error)
		Update(ctx context.Context, data *Pictures) error
		Delete(ctx context.Context, id int64) error
	}

	defaultPicturesModel struct {
		sqlc.CachedConn
		table string
	}

	Pictures struct {
		Id            int64           `db:"id"`
		Url           string          `db:"url"`
		Name          string          `db:"name"`
		Introduction  sql.NullString  `db:"introduction"`
		Category      sql.NullString  `db:"category"`
		Tags          sql.NullString  `db:"tags"`
		PicSize       sql.NullInt64   `db:"picSize"`
		PicWidth      sql.NullInt64   `db:"picWidth"`
		PicHeight     sql.NullInt64   `db:"picHeight"`
		PicScale      sql.NullFloat64 `db:"picScale"`
		PicFormat     sql.NullString  `db:"picFormat"`
		UserId        int64           `db:"userId"`
		CreateTime    time.Time       `db:"createTime"`
		EditTime      time.Time       `db:"editTime"`
		UpdateTime    time.Time       `db:"updateTime"`
		ReviewStatus  int64           `db:"reviewStatus"`
		ReviewMessage sql.NullString  `db:"reviewMessage"`
		ReviewerId    sql.NullInt64   `db:"reviewerId"`
		ReviewTime    sql.NullTime    `db:"reviewTime"`
		PicColor      sql.NullString  `db:"picColor"`
		ViewCount     int64           `db:"viewCount"`
		LikeCount     int64           `db:"likeCount"`
		IsDelete      int64           `db:"isDelete"`
	}
)

func newPicturesModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultPicturesModel {
	return &defaultPicturesModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`pictures`",
	}
}

func (m *defaultPicturesModel) Delete(ctx context.Context, id int64) error {
	picturesIdKey := fmt.Sprintf("%s%v", cachePicturesIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (sql.Result, error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, picturesIdKey)
	return err
}

func (m *defaultPicturesModel) FindOne(ctx context.Context, id int64) (*Pictures, error) {
	picturesIdKey := fmt.Sprintf("%s%v", cachePicturesIdPrefix, id)
	var resp Pictures
	err := m.QueryRowCtx(ctx, &resp, picturesIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", picturesRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPicturesModel) Insert(ctx context.Context, data *Pictures) (sql.Result, error) {
	picturesIdKey := fmt.Sprintf("%s%v", cachePicturesIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (sql.Result, error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, picturesRowsExpectAutoSet)
		return conn.ExecCtx(
			ctx,
			query,
			data.Url,
			data.Name,
			data.Introduction,
			data.Category,
			data.Tags,
			data.PicSize,
			data.PicWidth,
			data.PicHeight,
			data.PicScale,
			data.PicFormat,
			data.UserId,
			data.CreateTime,
			data.EditTime,
			data.UpdateTime,
			data.ReviewStatus,
			data.ReviewMessage,
			data.ReviewerId,
			data.ReviewTime,
			data.PicColor,
			data.ViewCount,
			data.LikeCount,
			data.IsDelete,
		)
	}, picturesIdKey)
	return ret, err
}

func (m *defaultPicturesModel) Update(ctx context.Context, data *Pictures) error {
	picturesIdKey := fmt.Sprintf("%s%v", cachePicturesIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (sql.Result, error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, picturesRowsWithPlaceHolder)
		return conn.ExecCtx(
			ctx,
			query,
			data.Url,
			data.Name,
			data.Introduction,
			data.Category,
			data.Tags,
			data.PicSize,
			data.PicWidth,
			data.PicHeight,
			data.PicScale,
			data.PicFormat,
			data.UserId,
			data.CreateTime,
			data.EditTime,
			data.UpdateTime,
			data.ReviewStatus,
			data.ReviewMessage,
			data.ReviewerId,
			data.ReviewTime,
			data.PicColor,
			data.ViewCount,
			data.LikeCount,
			data.IsDelete,
			data.Id,
		)
	}, picturesIdKey)
	return err
}

func (m *defaultPicturesModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cachePicturesIdPrefix, primary)
}

func (m *defaultPicturesModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", picturesRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultPicturesModel) tableName() string {
	return m.table
}
