// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	picture "photo-album/internal/handler/picture"
	user "photo-album/internal/handler/user"
	logicpicture "photo-album/internal/logic/picture"
	"photo-album/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/picture/delete",
				Handler: picture.DeletePictureHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/picture/get/vo",
				Handler: picture.GetPictureVOHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/picture/get",
				Handler: picture.GetPictureAdminHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/picture/review",
				Handler: picture.ReviewPictureHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/picture/home/carousel",
				Handler: picture.HomeCarouselHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/picture/list/page/vo",
				Handler: picture.ListPictureVOHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/picture/my/list/page",
				Handler: picture.ListMyPictureHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/picture/list/page",
				Handler: picture.ListPictureHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/picture/upload/url",
				Handler: picture.UploadPictureByUrlHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/picture/:id",
				Handler: picture.GetPictureHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/get/vo",
				Handler: user.GetUserVOHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/my",
				Handler: user.GetMyUserHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/my",
				Handler: user.UpdateMyUserHandler(serverCtx),
			},
			{
				Method:  http.MethodPatch,
				Path:    "/user/my",
				Handler: user.UpdateMyUserHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: user.LoginUserHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/register",
				Handler: user.RegisterUserHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)

	server.AddRoute(
		rest.Route{
			Method:  http.MethodPost,
			Path:    "/picture/upload",
			Handler: picture.UploadPictureHandler(serverCtx),
		},
		rest.WithPrefix("/api"),
		rest.WithMaxBytes(logicpicture.MaxFileUploadSize),
	)
}
