CREATE TABLE IF NOT EXISTS `pictures`
(
    `id`            bigint(20)   NOT NULL AUTO_INCREMENT COMMENT 'id',
    `url`           varchar(512) NOT NULL DEFAULT '' COMMENT '图片 url',
    `name`          varchar(128) NOT NULL DEFAULT '' COMMENT '图片名称',
    `introduction`  varchar(512)          DEFAULT NULL COMMENT '简介',
    `category`      varchar(64)           DEFAULT NULL COMMENT '分类',
    `tags`          varchar(512)          DEFAULT NULL COMMENT '标签（JSON 数组）',
    `picSize`       bigint(20)            DEFAULT NULL COMMENT '图片体积',
    `picWidth`      int(11)               DEFAULT NULL COMMENT '图片宽度',
    `picHeight`     int(11)               DEFAULT NULL COMMENT '图片高度',
    `picScale`      double                DEFAULT NULL COMMENT '图片宽高比例',
    `picFormat`     varchar(32)           DEFAULT NULL COMMENT '图片格式',
    `userId`        bigint(20)   NOT NULL DEFAULT '0' COMMENT '创建用户 id',
    `createTime`    datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `editTime`      datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '编辑时间',
    `updateTime`    datetime     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `reviewStatus`  int(11)      NOT NULL DEFAULT '0' COMMENT '审核状态：0-待审核; 1-通过; 2-拒绝',
    `reviewMessage` varchar(512)          DEFAULT NULL COMMENT '审核信息',
    `reviewerId`    bigint(20)            DEFAULT NULL COMMENT '审核人 ID',
    `reviewTime`    datetime              DEFAULT NULL COMMENT '审核时间',
    `picColor`      varchar(16)           DEFAULT NULL COMMENT '图片主色调',
    `viewCount`     bigint(20)   NOT NULL DEFAULT '0' COMMENT '浏览次数',
    `likeCount`     bigint(20)   NOT NULL DEFAULT '0' COMMENT '点赞次数',
    `isDelete`      tinyint(4)   NOT NULL DEFAULT '0' COMMENT '是否删除',
    PRIMARY KEY (`id`),
    KEY `idx_name` (`name`),
    KEY `idx_introduction` (`introduction`),
    KEY `idx_category` (`category`),
    KEY `idx_tags` (`tags`),
    KEY `idx_userId` (`userId`),
    KEY `idx_reviewStatus` (`reviewStatus`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci COMMENT ='图片';
